language: shell
os: linux
dist: trusty

services:
  - docker
  
install:
  - sudo apt-get install -y net-tools
  - sudo ./install_requirements.sh
  - sudo ./load_image.sh
  
before_script:
  - sudo ./start.sh 

script:
  - sudo ./test.sh

after_script:
  - sudo ./stop.sh
