sudo: required

services:
  - docker
 
before_install:
  - sudo apt-get update
  - sudo apt-get install iputils-ping
  
install:
  - ./install_docker_ovs.sh

script:
  - ./load_image.sh
  - ./start.sh
  - ./test.sh
  - ./stop.sh
